sudo: false
language: java

before_cache:
  # No sense in caching current build artifacts
  - rm -rf $HOME/.m2/repository/org/xipki

cache:
  directories:
    - $HOME/.m2/repository

cache:
  directories:
    - $HOME/.m2/repository

script:
  - mvn clean install

notifications:
  email: false
